<style data-type="vc_shortcodes-custom-css">.vc_custom_1774353520781{margin-bottom: -10px !important;}</style><link rel='stylesheet' id='wpra-lightbox-css' href='https://leano.crackerjackdemo.co.za/wp-content/plugins/wp-rss-aggregator/core/css/jquery-colorbox.css?ver=1.4.33' media='all' />
<div class="vc_grid vc_row vc_grid-gutter-30px vc_pageable-wrapper vc_hook_hover" data-vc-pageable-content="true"><div class="vc_grid-item vc_clearfix vc_col-sm-4 vc_grid-item-zone-c-top"><div class="vc_grid-item-mini vc_clearfix "><div class="vc_gitem-zone vc_gitem-zone-c"><div class="vc_gitem-zone-mini"><div class="vc_gitem_row vc_row vc_gitem-row-position-top"><div class="vc_col-sm-12 vc_gitem-col vc_gitem-col-align-">
	<div class="wpb_single_image wpb_content_element vc_align_">
		<figure class="wpb_wrapper vc_figure">
			<a href="https://leano.crackerjackdemo.co.za/news/diesel-in-south-africa-the-fuel-that-powers-a-nation/" class="vc_gitem-link vc_single_image-wrapper vc_box_border_grey" title="Diesel in South Africa: The Fuel That Powers a Nation"><img width="1200" height="630" src="https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/The-Fuel-That-Powers-a-Nation.jpg" class="vc_single_image-img attachment-full" alt="The Fuel That Powers a Nation" title="The Fuel That Powers a Nation" srcset="https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/The-Fuel-That-Powers-a-Nation.jpg 1200w, https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/The-Fuel-That-Powers-a-Nation-300x158.jpg 300w, https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/The-Fuel-That-Powers-a-Nation-1024x538.jpg 1024w, https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/The-Fuel-That-Powers-a-Nation-768x403.jpg 768w" sizes="(max-width: 1200px) 100vw, 1200px" /></a>
		</figure>
	</div>
<div class="vc_custom_heading title-h3 vc_custom_1774353520781 vc_gitem-post-data vc_gitem-post-data-source-post_title" ><div style="text-align: left" ><a href="https://leano.crackerjackdemo.co.za/news/diesel-in-south-africa-the-fuel-that-powers-a-nation/" class="vc_gitem-link" title="Diesel in South Africa: The Fuel That Powers a Nation">Diesel in South Africa: The Fuel That Powers a Nation</a></div></div><div class="vc_custom_heading vc_gitem-post-data vc_gitem-post-data-source-post_excerpt" ><p style="text-align: left" ><p>Discover how diesel powers South Africa&#8217;s economy, from road logistics and mining to agriculture and manufacturing. Read our full analysis.</p>
</p></div><div class="vc_btn3-container  newsgrid-btn vc_btn3-inline"><a class="vc_general vc_btn3 vc_btn3-size-md vc_btn3-shape-square vc_btn3-style-flat vc_btn3-color-warning" a href="https://leano.crackerjackdemo.co.za/news/diesel-in-south-africa-the-fuel-that-powers-a-nation/" class="vc_gitem-link vc_general vc_btn3 vc_general vc_btn3 vc_btn3-size-md vc_btn3-shape-square vc_btn3-style-flat vc_btn3-color-warning newsgrid-btn" title="Read More">Read More</a></div></div></div></div></div><div class="vc_gitem-animated-block" ></div></div><div class="vc_clearfix"></div></div><div class="vc_grid-item vc_clearfix vc_col-sm-4 vc_grid-item-zone-c-top"><div class="vc_grid-item-mini vc_clearfix "><div class="vc_gitem-zone vc_gitem-zone-c"><div class="vc_gitem-zone-mini"><div class="vc_gitem_row vc_row vc_gitem-row-position-top"><div class="vc_col-sm-12 vc_gitem-col vc_gitem-col-align-">
	<div class="wpb_single_image wpb_content_element vc_align_">
		<figure class="wpb_wrapper vc_figure">
			<a href="https://leano.crackerjackdemo.co.za/news/diesel-is-not-going-anywhere-the-decades-long-reality-of-south-africas-energy-future/" class="vc_gitem-link vc_single_image-wrapper vc_box_border_grey" title="Diesel Is Not Going Anywhere: The Decades-Long Reality of South Africa&#8217;s Energy Future"><img width="1200" height="630" src="https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/Diesel-Is-Not-Going-Anywhere.jpg" class="vc_single_image-img attachment-full" alt="Diesel Is Not Going Anywhere" title="Diesel Is Not Going Anywhere" srcset="https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/Diesel-Is-Not-Going-Anywhere.jpg 1200w, https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/Diesel-Is-Not-Going-Anywhere-300x158.jpg 300w, https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/Diesel-Is-Not-Going-Anywhere-1024x538.jpg 1024w, https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/Diesel-Is-Not-Going-Anywhere-768x403.jpg 768w" sizes="(max-width: 1200px) 100vw, 1200px" /></a>
		</figure>
	</div>
<div class="vc_custom_heading title-h3 vc_custom_1774353520781 vc_gitem-post-data vc_gitem-post-data-source-post_title" ><div style="text-align: left" ><a href="https://leano.crackerjackdemo.co.za/news/diesel-is-not-going-anywhere-the-decades-long-reality-of-south-africas-energy-future/" class="vc_gitem-link" title="Diesel Is Not Going Anywhere: The Decades-Long Reality of South Africa&#8217;s Energy Future">Diesel Is Not Going Anywhere: The Decades-Long Reality of South Africa&#8217;s Energy Future</a></div></div><div class="vc_custom_heading vc_gitem-post-data vc_gitem-post-data-source-post_excerpt" ><p style="text-align: left" ><p>Explore why diesel remains essential for South Africa’s energy future despite global EV trends. A grounded look at the 2026 energy landscape.</p>
</p></div><div class="vc_btn3-container  newsgrid-btn vc_btn3-inline"><a class="vc_general vc_btn3 vc_btn3-size-md vc_btn3-shape-square vc_btn3-style-flat vc_btn3-color-warning" a href="https://leano.crackerjackdemo.co.za/news/diesel-is-not-going-anywhere-the-decades-long-reality-of-south-africas-energy-future/" class="vc_gitem-link vc_general vc_btn3 vc_general vc_btn3 vc_btn3-size-md vc_btn3-shape-square vc_btn3-style-flat vc_btn3-color-warning newsgrid-btn" title="Read More">Read More</a></div></div></div></div></div><div class="vc_gitem-animated-block" ></div></div><div class="vc_clearfix"></div></div><div class="vc_grid-item vc_clearfix vc_col-sm-4 vc_grid-item-zone-c-top"><div class="vc_grid-item-mini vc_clearfix "><div class="vc_gitem-zone vc_gitem-zone-c"><div class="vc_gitem-zone-mini"><div class="vc_gitem_row vc_row vc_gitem-row-position-top"><div class="vc_col-sm-12 vc_gitem-col vc_gitem-col-align-">
	<div class="wpb_single_image wpb_content_element vc_align_">
		<figure class="wpb_wrapper vc_figure">
			<a href="https://leano.crackerjackdemo.co.za/news/diesel-pricing-in-south-africa-what-youre-really-paying-for-at-the-pump/" class="vc_gitem-link vc_single_image-wrapper vc_box_border_grey" title="Diesel Pricing in South Africa: What You&#8217;re Really Paying For at the Pump"><img width="1200" height="630" src="https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/Diesel-Pricing-in-South-Africa.jpg" class="vc_single_image-img attachment-full" alt="Diesel Pricing in South Africa" title="Diesel Pricing in South Africa" srcset="https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/Diesel-Pricing-in-South-Africa.jpg 1200w, https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/Diesel-Pricing-in-South-Africa-300x158.jpg 300w, https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/Diesel-Pricing-in-South-Africa-1024x538.jpg 1024w, https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/Diesel-Pricing-in-South-Africa-768x403.jpg 768w" sizes="(max-width: 1200px) 100vw, 1200px" /></a>
		</figure>
	</div>
<div class="vc_custom_heading title-h3 vc_custom_1774353520781 vc_gitem-post-data vc_gitem-post-data-source-post_title" ><div style="text-align: left" ><a href="https://leano.crackerjackdemo.co.za/news/diesel-pricing-in-south-africa-what-youre-really-paying-for-at-the-pump/" class="vc_gitem-link" title="Diesel Pricing in South Africa: What You&#8217;re Really Paying For at the Pump">Diesel Pricing in South Africa: What You&#8217;re Really Paying For at the Pump</a></div></div><div class="vc_custom_heading vc_gitem-post-data vc_gitem-post-data-source-post_excerpt" ><p style="text-align: left" ><p>Understand the complex global and local factors behind South Africa&#8217;s diesel prices, from international crude costs to domestic government levies.</p>
</p></div><div class="vc_btn3-container  newsgrid-btn vc_btn3-inline"><a class="vc_general vc_btn3 vc_btn3-size-md vc_btn3-shape-square vc_btn3-style-flat vc_btn3-color-warning" a href="https://leano.crackerjackdemo.co.za/news/diesel-pricing-in-south-africa-what-youre-really-paying-for-at-the-pump/" class="vc_gitem-link vc_general vc_btn3 vc_general vc_btn3 vc_btn3-size-md vc_btn3-shape-square vc_btn3-style-flat vc_btn3-color-warning newsgrid-btn" title="Read More">Read More</a></div></div></div></div></div><div class="vc_gitem-animated-block" ></div></div><div class="vc_clearfix"></div></div><div class="vc_grid-item vc_clearfix vc_col-sm-4 vc_grid-item-zone-c-top"><div class="vc_grid-item-mini vc_clearfix "><div class="vc_gitem-zone vc_gitem-zone-c"><div class="vc_gitem-zone-mini"><div class="vc_gitem_row vc_row vc_gitem-row-position-top"><div class="vc_col-sm-12 vc_gitem-col vc_gitem-col-align-">
	<div class="wpb_single_image wpb_content_element vc_align_">
		<figure class="wpb_wrapper vc_figure">
			<a href="https://leano.crackerjackdemo.co.za/news/from-coal-fields-to-your-tank-the-production-journey-of-diesel-in-south-africa/" class="vc_gitem-link vc_single_image-wrapper vc_box_border_grey" title="From Coal Fields to Your Tank: The Production Journey of Diesel in South Africa"><img width="1200" height="630" src="https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/The-Production-Journey-of-Diesel-in-South-Africa.jpg" class="vc_single_image-img attachment-full" alt="" title="The-Production-Journey-of-Diesel-in-South-Africa" srcset="https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/The-Production-Journey-of-Diesel-in-South-Africa.jpg 1200w, https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/The-Production-Journey-of-Diesel-in-South-Africa-300x158.jpg 300w, https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/The-Production-Journey-of-Diesel-in-South-Africa-1024x538.jpg 1024w, https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/The-Production-Journey-of-Diesel-in-South-Africa-768x403.jpg 768w" sizes="(max-width: 1200px) 100vw, 1200px" /></a>
		</figure>
	</div>
<div class="vc_custom_heading title-h3 vc_custom_1774353520781 vc_gitem-post-data vc_gitem-post-data-source-post_title" ><div style="text-align: left" ><a href="https://leano.crackerjackdemo.co.za/news/from-coal-fields-to-your-tank-the-production-journey-of-diesel-in-south-africa/" class="vc_gitem-link" title="From Coal Fields to Your Tank: The Production Journey of Diesel in South Africa">From Coal Fields to Your Tank: The Production Journey of Diesel in South Africa</a></div></div><div class="vc_custom_heading vc_gitem-post-data vc_gitem-post-data-source-post_excerpt" ><p style="text-align: left" ><p>Follow the journey of diesel in South Africa, from imported crude and local coal-to-liquids technology to the network that fuels the nation.</p>
</p></div><div class="vc_btn3-container  newsgrid-btn vc_btn3-inline"><a class="vc_general vc_btn3 vc_btn3-size-md vc_btn3-shape-square vc_btn3-style-flat vc_btn3-color-warning" a href="https://leano.crackerjackdemo.co.za/news/from-coal-fields-to-your-tank-the-production-journey-of-diesel-in-south-africa/" class="vc_gitem-link vc_general vc_btn3 vc_general vc_btn3 vc_btn3-size-md vc_btn3-shape-square vc_btn3-style-flat vc_btn3-color-warning newsgrid-btn" title="Read More">Read More</a></div></div></div></div></div><div class="vc_gitem-animated-block" ></div></div><div class="vc_clearfix"></div></div><div class="vc_grid-item vc_clearfix vc_col-sm-4 vc_grid-item-zone-c-top"><div class="vc_grid-item-mini vc_clearfix "><div class="vc_gitem-zone vc_gitem-zone-c"><div class="vc_gitem-zone-mini"><div class="vc_gitem_row vc_row vc_gitem-row-position-top"><div class="vc_col-sm-12 vc_gitem-col vc_gitem-col-align-">
	<div class="wpb_single_image wpb_content_element vc_align_">
		<figure class="wpb_wrapper vc_figure">
			<a href="https://leano.crackerjackdemo.co.za/news/lead-in-fuel-south-africas-long-road-to-clean-diesel/" class="vc_gitem-link vc_single_image-wrapper vc_box_border_grey" title="Lead in Fuel: South Africa&#8217;s Long Road to Clean Diesel"><img width="1200" height="630" src="https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/South-Africas-Long-Road-to-Clean-Diesel.jpg" class="vc_single_image-img attachment-full" alt="South Africas Long Road to Clean Diesel" title="South Africas Long Road to Clean Diesel" srcset="https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/South-Africas-Long-Road-to-Clean-Diesel.jpg 1200w, https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/South-Africas-Long-Road-to-Clean-Diesel-300x158.jpg 300w, https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/South-Africas-Long-Road-to-Clean-Diesel-1024x538.jpg 1024w, https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/South-Africas-Long-Road-to-Clean-Diesel-768x403.jpg 768w" sizes="(max-width: 1200px) 100vw, 1200px" /></a>
		</figure>
	</div>
<div class="vc_custom_heading title-h3 vc_custom_1774353520781 vc_gitem-post-data vc_gitem-post-data-source-post_title" ><div style="text-align: left" ><a href="https://leano.crackerjackdemo.co.za/news/lead-in-fuel-south-africas-long-road-to-clean-diesel/" class="vc_gitem-link" title="Lead in Fuel: South Africa&#8217;s Long Road to Clean Diesel">Lead in Fuel: South Africa&#8217;s Long Road to Clean Diesel</a></div></div><div class="vc_custom_heading vc_gitem-post-data vc_gitem-post-data-source-post_excerpt" ><p style="text-align: left" ><p>From high lead levels to the 2027 clean diesel goal, explore South Africa’s hard-won journey toward safer fuel and better public health.</p>
</p></div><div class="vc_btn3-container  newsgrid-btn vc_btn3-inline"><a class="vc_general vc_btn3 vc_btn3-size-md vc_btn3-shape-square vc_btn3-style-flat vc_btn3-color-warning" a href="https://leano.crackerjackdemo.co.za/news/lead-in-fuel-south-africas-long-road-to-clean-diesel/" class="vc_gitem-link vc_general vc_btn3 vc_general vc_btn3 vc_btn3-size-md vc_btn3-shape-square vc_btn3-style-flat vc_btn3-color-warning newsgrid-btn" title="Read More">Read More</a></div></div></div></div></div><div class="vc_gitem-animated-block" ></div></div><div class="vc_clearfix"></div></div><div class="vc_grid-item vc_clearfix vc_col-sm-4 vc_grid-item-zone-c-top"><div class="vc_grid-item-mini vc_clearfix "><div class="vc_gitem-zone vc_gitem-zone-c"><div class="vc_gitem-zone-mini"><div class="vc_gitem_row vc_row vc_gitem-row-position-top"><div class="vc_col-sm-12 vc_gitem-col vc_gitem-col-align-">
	<div class="wpb_single_image wpb_content_element vc_align_">
		<figure class="wpb_wrapper vc_figure">
			<a href="https://leano.crackerjackdemo.co.za/news/the-hidden-adulterant-in-your-tank-why-fuel-washing-threatens-south-africa-when-it-can-least-afford-it/" class="vc_gitem-link vc_single_image-wrapper vc_box_border_grey" title="The hidden adulterant in your tank: why fuel washing threatens South Africa when it can least afford it"><img width="1200" height="630" src="https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/The-hidden-adulterant.jpg" class="vc_single_image-img attachment-full" alt="The hidden adulterant" title="The hidden adulterant" srcset="https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/The-hidden-adulterant.jpg 1200w, https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/The-hidden-adulterant-300x158.jpg 300w, https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/The-hidden-adulterant-1024x538.jpg 1024w, https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/04/The-hidden-adulterant-768x403.jpg 768w" sizes="(max-width: 1200px) 100vw, 1200px" /></a>
		</figure>
	</div>
<div class="vc_custom_heading title-h3 vc_custom_1774353520781 vc_gitem-post-data vc_gitem-post-data-source-post_title" ><div style="text-align: left" ><a href="https://leano.crackerjackdemo.co.za/news/the-hidden-adulterant-in-your-tank-why-fuel-washing-threatens-south-africa-when-it-can-least-afford-it/" class="vc_gitem-link" title="The hidden adulterant in your tank: why fuel washing threatens South Africa when it can least afford it">The hidden adulterant in your tank: why fuel washing threatens South Africa when it can least afford it</a></div></div><div class="vc_custom_heading vc_gitem-post-data vc_gitem-post-data-source-post_excerpt" ><p style="text-align: left" ><p>Diesel prices just saw the largest surge in SA history. Learn how fuel washing syndicates exploit this crisis and the true cost to your engines.</p>
</p></div><div class="vc_btn3-container  newsgrid-btn vc_btn3-inline"><a class="vc_general vc_btn3 vc_btn3-size-md vc_btn3-shape-square vc_btn3-style-flat vc_btn3-color-warning" a href="https://leano.crackerjackdemo.co.za/news/the-hidden-adulterant-in-your-tank-why-fuel-washing-threatens-south-africa-when-it-can-least-afford-it/" class="vc_gitem-link vc_general vc_btn3 vc_general vc_btn3 vc_btn3-size-md vc_btn3-shape-square vc_btn3-style-flat vc_btn3-color-warning newsgrid-btn" title="Read More">Read More</a></div></div></div></div></div><div class="vc_gitem-animated-block" ></div></div><div class="vc_clearfix"></div></div><div class="vc_grid-item vc_clearfix vc_col-sm-4 vc_grid-item-zone-c-top"><div class="vc_grid-item-mini vc_clearfix "><div class="vc_gitem-zone vc_gitem-zone-c"><div class="vc_gitem-zone-mini"><div class="vc_gitem_row vc_row vc_gitem-row-position-top"><div class="vc_col-sm-12 vc_gitem-col vc_gitem-col-align-">
	<div class="wpb_single_image wpb_content_element vc_align_">
		<figure class="wpb_wrapper vc_figure">
			<a href="https://leano.crackerjackdemo.co.za/news/lorem-ipsum/" class="vc_gitem-link vc_single_image-wrapper vc_box_border_grey" title="Lorem ipsum"><img width="600" height="369" src="https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/03/Fuel-Management-Solutions.webp" class="vc_single_image-img attachment-full" alt="" title="Fuel-Management-Solutions" srcset="https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/03/Fuel-Management-Solutions.webp 600w, https://leano.crackerjackdemo.co.za/wp-content/uploads/2026/03/Fuel-Management-Solutions-300x185.webp 300w" sizes="(max-width: 600px) 100vw, 600px" /></a>
		</figure>
	</div>
<div class="vc_custom_heading title-h3 vc_custom_1774353520781 vc_gitem-post-data vc_gitem-post-data-source-post_title" ><div style="text-align: left" ><a href="https://leano.crackerjackdemo.co.za/news/lorem-ipsum/" class="vc_gitem-link" title="Lorem ipsum">Lorem ipsum</a></div></div><div class="vc_custom_heading vc_gitem-post-data vc_gitem-post-data-source-post_excerpt" ><p style="text-align: left" ><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
</p></div><div class="vc_btn3-container  newsgrid-btn vc_btn3-inline"><a class="vc_general vc_btn3 vc_btn3-size-md vc_btn3-shape-square vc_btn3-style-flat vc_btn3-color-warning" a href="https://leano.crackerjackdemo.co.za/news/lorem-ipsum/" class="vc_gitem-link vc_general vc_btn3 vc_general vc_btn3 vc_btn3-size-md vc_btn3-shape-square vc_btn3-style-flat vc_btn3-color-warning newsgrid-btn" title="Read More">Read More</a></div></div></div></div></div><div class="vc_gitem-animated-block" ></div></div><div class="vc_clearfix"></div></div></div>